#!/usr/bin/env zsh

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"

FONT_FACE="Hack Nerd Font"

PLUGIN_DIR="$SKETCHYBAR_CONFIG/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

FONT_COLOR=0xFFCAD3F5
ITEM_SURFACE=0xFF363A4F

sketchybar --bar \
    height=32 \
    color=0xEF24273A \
    margin=0 \
    sticky=on \
    padding_left=10 \
    padding_right=10 \
    notch_width=225 \
    display=all

source "$PLUGIN_DIR/apple.sh"

sketchybar --default \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Regular:20.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Regular:16.0" \
    label.color=$FONT_COLOR \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify e \
    --set spotify \
    icon= \
    icon.font="$FONT_FACE:Bold:20.0" \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xFFF5BDE6 \
    icon.color=0xff24273a \
    label.drawing=off \
    script="$PLUGIN_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xFFA6DA95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    icon.color=0xFF24273A \
    label.drawing=no \
    script="$PLUGIN_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    background.padding_left=-3 \
    icon= \
    icon.color=0xFFA6DA95 \
    icon.font="$FONT_FACE:Bold:21.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=0 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:12.0" \
    label.drawing=yes

sketchybar --add item hostname.flag q \
    --set hostname.flag \
    background.color=$ITEM_SURFACE \
    icon=🏳️‍⚧️ \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.drawing=off \

sketchybar --add item hostname q \
    --set hostname \
    background.color=$ITEM_SURFACE \
    icon=󰇄 \
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Regular:15.0" \
    label="$(hostname)"

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=1 \
    script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    script="$PLUGIN_DIR/volume.sh" \
    --subscribe volume volume_change

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
