-- Keymaps
local map = vim.keymap
require("nvim-dap-virtual-text").setup()

map.set('n', '<F5>', function()
    require('dap').continue()
end)
map.set('n', '<F10>', function() require('dap').step_over() end)
map.set('n', '<F11>', function() require('dap').step_into() end)
map.set('n', '<F12>', function() require('dap').step_out() end)
map.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end)
map.set('n', '<Leader>B', function() require('dap').set_breakpoint() end)
map.set('n', '<Leader>lp', function() require('dap').set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end)
map.set('n', '<Leader>dr', function() require('dap').repl.open() end)
map.set('n', '<Leader>dl', function() require('dap').run_last() end)
map.set({'n', 'v'}, '<Leader>dh', function() require('dap.ui.widgets').hover() end)
map.set({'n', 'v'}, '<Leader>dp', function() require('dap.ui.widgets').preview() end)
map.set('n', '<Leader>df', function()
    local widgets = require('dap.ui.widgets')
    widgets.centered_float(widgets.frames)
end)
map.set('n', '<Leader>ds', function()
    local widgets = require('dap.ui.widgets')
    widgets.centered_float(widgets.scopes)
end)
map.set('n', '<Leader>dc', function() require('dapui').close() end)
